language: node_js
node_js: 10
install:
    - npm install
script:
    - npm test
after_success:
    - npm run build
before_deploy:
    - cp package.json $TRAVIS_BUILD_DIR/dist/src/
deploy:
    skip_cleanup: true
    provider: script
    script: npm publish $TRAVIS_BUILD_DIR/dist/src
    on:
        tags: true
